name: Nuxtjs Simple

on: [push]

jobs:
  nuxtjs-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: move to project dir
        run: |
          cd front
      - name: Install Dependencies
        run: |
          npm ci
      - name: Execute tests
        run: |
          npm run lint
